org.cheminfo.my_rdk_nodes: # {group_id}.{name} from the knime.yml
  src: /home/iwatobipen/dev/rdkitugm2023_hackathon/python_knime_node/cheminfo_extension # Path to folder containing the extension files
  conda_env_path: /home/iwatobipen/miniconda3/envs/knime5_node_dev # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
